
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - rabbitmq
    command: python3 new_app.py
  rabbitmq:
    image: "rabbitmq:3.8.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  celery_worker:
    build: .
    command: celery -A celery_working worker --loglevel=info --pool=solo
    depends_on:
      - rabbitmq